# Site settings
title: ブログ
description: ブログ
url: https://bitoku.github.io/
baseurl: "" # Set this to the subpath of your site if it exists in a subdirectory (e.g. /blog)

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
 - jekyll-remote-theme
